[2024-11-05T12:54:16.039+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T12:54:16.054+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T12:54:13.545985+00:00 [queued]>
[2024-11-05T12:54:16.063+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T12:54:13.545985+00:00 [queued]>
[2024-11-05T12:54:16.064+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-05T12:54:16.078+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_api> on 2024-11-05 12:54:13.545985+00:00
[2024-11-05T12:54:16.086+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'test_api', 'manual__2024-11-05T12:54:13.545985+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmphgdw1ig0']
[2024-11-05T12:54:16.088+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask test_api
[2024-11-05T12:54:16.089+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2802) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-05T12:54:16.090+0000] {standard_task_runner.py:72} INFO - Started process 2803 to run task
[2024-11-05T12:54:16.131+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.test_api manual__2024-11-05T12:54:13.545985+00:00 [running]> on host 68d32cd9cfe4
[2024-11-05T12:54:16.318+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='test_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T12:54:13.545985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T12:54:13.545985+00:00'
[2024-11-05T12:54:16.319+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T12:54:16.329+0000] {logging_mixin.py:190} INFO - 2024-11-05 12:54:16.329208
[2024-11-05T12:54:16.532+0000] {logging_mixin.py:190} INFO - Exception when get request : 'weather'
[2024-11-05T12:54:16.533+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-05T12:54:16.542+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T12:54:16.544+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_test_v1, task_id=test_api, run_id=manual__2024-11-05T12:54:13.545985+00:00, execution_date=20241105T125413, start_date=20241105T125416, end_date=20241105T125416
[2024-11-05T12:54:16.590+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T12:54:16.609+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T12:54:16.613+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
