[2024-11-15T10:25:14.060+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T10:25:14.079+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.spark-submit manual__2024-11-15T10:20:07.927185+00:00 [queued]>
[2024-11-15T10:25:14.089+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.spark-submit manual__2024-11-15T10:20:07.927185+00:00 [queued]>
[2024-11-15T10:25:14.090+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 6
[2024-11-15T10:25:14.108+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): spark-submit> on 2024-11-15 10:20:07.927185+00:00
[2024-11-15T10:25:14.118+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'spark-submit', 'manual__2024-11-15T10:20:07.927185+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmp1v4kt_93']
[2024-11-15T10:25:14.122+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask spark-submit
[2024-11-15T10:25:14.121+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-15T10:25:14.123+0000] {standard_task_runner.py:72} INFO - Started process 248 to run task
[2024-11-15T10:25:14.175+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.spark-submit manual__2024-11-15T10:20:07.927185+00:00 [running]> on host 67dcec6827c3
[2024-11-15T10:25:14.258+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='spark-submit' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T10:20:07.927185+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T10:20:07.927185+00:00'
[2024-11-15T10:25:14.259+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T10:25:14.290+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-11-15T10:25:14.292+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --name arrow-spark --deploy-mode client /jobs/pysparksubmitoperator.py
[2024-11-15T10:25:14.340+0000] {spark_submit.py:634} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-11-15T10:25:16.351+0000] {spark_submit.py:634} INFO - python3: can't open file '/jobs/pysparksubmitoperator.py': [Errno 2] No such file or directory
[2024-11-15T10:25:16.365+0000] {spark_submit.py:634} INFO - 24/11/15 10:25:16 INFO ShutdownHookManager: Shutdown hook called
[2024-11-15T10:25:16.368+0000] {spark_submit.py:634} INFO - 24/11/15 10:25:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-79d1a904-e7f7-4188-8972-ab7bbff8ca3c
[2024-11-15T10:25:16.417+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --name arrow-spark --deploy-mode client /jobs/pysparksubmitoperator.py. Error code is: 2.
[2024-11-15T10:25:16.429+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=api_test_v1, task_id=spark-submit, run_id=manual__2024-11-15T10:20:07.927185+00:00, execution_date=20241115T102007, start_date=20241115T102514, end_date=20241115T102516
[2024-11-15T10:25:16.448+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T10:25:16.450+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task spark-submit (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --name arrow-spark --deploy-mode client /jobs/pysparksubmitoperator.py. Error code is: 2.; 248)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --name arrow-spark --deploy-mode client /jobs/pysparksubmitoperator.py. Error code is: 2.
[2024-11-15T10:25:16.470+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-15T10:25:16.486+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T10:25:16.488+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
