[2024-11-05T12:59:01.652+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T12:59:01.669+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T12:58:59.756838+00:00 [queued]>
[2024-11-05T12:59:01.677+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T12:58:59.756838+00:00 [queued]>
[2024-11-05T12:59:01.679+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-05T12:59:01.694+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_api> on 2024-11-05 12:58:59.756838+00:00
[2024-11-05T12:59:01.702+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'test_api', 'manual__2024-11-05T12:58:59.756838+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmpy6jy5frd']
[2024-11-05T12:59:01.705+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask test_api
[2024-11-05T12:59:01.705+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2940) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-05T12:59:01.707+0000] {standard_task_runner.py:72} INFO - Started process 2941 to run task
[2024-11-05T12:59:01.749+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.test_api manual__2024-11-05T12:58:59.756838+00:00 [running]> on host 68d32cd9cfe4
[2024-11-05T12:59:01.963+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='test_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T12:58:59.756838+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T12:58:59.756838+00:00'
[2024-11-05T12:59:01.965+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T12:59:01.978+0000] {logging_mixin.py:190} INFO - 2024-11-05 12:59:01.978036
[2024-11-05T12:59:02.158+0000] {logging_mixin.py:190} INFO - {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-11-05T12:59:02.159+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-05T12:59:02.169+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T12:59:02.170+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_test_v1, task_id=test_api, run_id=manual__2024-11-05T12:58:59.756838+00:00, execution_date=20241105T125859, start_date=20241105T125901, end_date=20241105T125902
[2024-11-05T12:59:02.205+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T12:59:02.219+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T12:59:02.223+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
