[2024-11-05T13:08:14.083+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:08:14.108+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T13:08:10.270390+00:00 [queued]>
[2024-11-05T13:08:14.124+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T13:08:10.270390+00:00 [queued]>
[2024-11-05T13:08:14.125+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-05T13:08:14.148+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_api> on 2024-11-05 13:08:10.270390+00:00
[2024-11-05T13:08:14.164+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'test_api', 'manual__2024-11-05T13:08:10.270390+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmpdn05twaz']
[2024-11-05T13:08:14.175+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask test_api
[2024-11-05T13:08:14.176+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-05T13:08:14.180+0000] {standard_task_runner.py:72} INFO - Started process 209 to run task
[2024-11-05T13:08:14.277+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.test_api manual__2024-11-05T13:08:10.270390+00:00 [running]> on host 0e1d1909ae51
[2024-11-05T13:08:14.599+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='test_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T13:08:10.270390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T13:08:10.270390+00:00'
[2024-11-05T13:08:14.601+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:08:14.632+0000] {logging_mixin.py:190} INFO - 2024-11-05 13:08:14.632466
[2024-11-05T13:08:14.633+0000] {logging_mixin.py:190} INFO - https://api.openweathermap.org/data/2.5/weather?lat=6.175108444784084&lon=49.111459997943115&appid=None
[2024-11-05T13:08:15.253+0000] {logging_mixin.py:190} INFO - {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-11-05T13:08:15.255+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-05T13:08:15.279+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:08:15.281+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_test_v1, task_id=test_api, run_id=manual__2024-11-05T13:08:10.270390+00:00, execution_date=20241105T130810, start_date=20241105T130814, end_date=20241105T130815
[2024-11-05T13:08:15.328+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T13:08:15.364+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:08:15.371+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
